### ISSUE TITLE
Doesn't work anymore? "Server returned an error. Please try again later."

### ISSUE THREAD

**Issue by KoStard** [alashow/datmusic#49]

**Comment by el-gonzo** [comment]
I'm now able to perform a search, but then if I try to download I get either an empty file (zero bytes) or a 500 page.
![screen shot 2018-08-21 at 11 10 02](https://user-images.githubusercontent.com/42541567/44392611-e7296e00-a532-11e8-92ea-a0e3b8ad52e2.png)

**Comment by alashow** [comment]
Fixed

**Comment by el-gonzo** [comment]
Not for me, still getting the `Server returned an error. Please try again later.`error message

**Comment by alashow** [comment]
Well damn. My bad. Try now

**Comment by el-gonzo** [comment]
Seems to be working now, thank you!

**Comment by alashow** [comment]
Fixed again..

**Comment by Incognito4nonymous** [comment]
Thanks ! Worked !
